"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        if key and key not in os.environ:
            os.environ[key] = value


def _env(name: str, default: str, *fallback_names: str) -> str:
    for env_name in (name, *fallback_names):
        value = os.getenv(env_name)
        if value is not None and value != "":
            return value
    return default


_load_env_file(BASE_DIR / ".env")
_load_env_file(BASE_DIR / ".env.local")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l@ng!i62=7om+pqpmf!z5ysp(9a61d-pgwj!81zk&8_b_8y*6x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.consumption',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

RUNNING_IN_DOCKER = os.getenv("RUNNING_IN_DOCKER") == "1" or Path("/.dockerenv").exists()
DEFAULT_POSTGRES_HOST = "host.docker.internal" if RUNNING_IN_DOCKER else "127.0.0.1"
DEFAULT_POSTGRES_PORT = "5432" if RUNNING_IN_DOCKER else "15432"
DEFAULT_POSTGRES_USER = _env("POSTGRES_USER", "student", "DASHBOARD_POSTGRES_USER")
DEFAULT_POSTGRES_PASSWORD = _env("POSTGRES_PASSWORD", "st1211@98w", "DASHBOARD_POSTGRES_PASSWORD")
POSTGRES_KEEPALIVE_OPTIONS = {
    "keepalives": int(os.getenv("POSTGRES_KEEPALIVES", "1")),
    "keepalives_idle": int(os.getenv("POSTGRES_KEEPALIVES_IDLE", "30")),
    "keepalives_interval": int(os.getenv("POSTGRES_KEEPALIVES_INTERVAL", "10")),
    "keepalives_count": int(os.getenv("POSTGRES_KEEPALIVES_COUNT", "5")),
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": _env("POSTGRES_HOST", DEFAULT_POSTGRES_HOST, "DASHBOARD_POSTGRES_HOST"),
        "PORT": _env("POSTGRES_PORT", DEFAULT_POSTGRES_PORT, "DASHBOARD_POSTGRES_PORT"),
        "NAME": os.getenv("DJANGO_POSTGRES_DB", "student"),
        "USER": os.getenv("DJANGO_POSTGRES_USER", DEFAULT_POSTGRES_USER),
        "PASSWORD": os.getenv("DJANGO_POSTGRES_PASSWORD", DEFAULT_POSTGRES_PASSWORD),
        "OPTIONS": {
            "connect_timeout": int(os.getenv("POSTGRES_CONNECT_TIMEOUT", "5")),
            "options": os.getenv("DJANGO_POSTGRES_OPTIONS", "-c search_path=student_schema,public"),
            **POSTGRES_KEEPALIVE_OPTIONS,
        },
    },
    "source": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": _env("SOURCE_POSTGRES_HOST", _env("POSTGRES_HOST", DEFAULT_POSTGRES_HOST, "DASHBOARD_POSTGRES_HOST")),
        "PORT": _env("SOURCE_POSTGRES_PORT", _env("POSTGRES_PORT", DEFAULT_POSTGRES_PORT, "DASHBOARD_POSTGRES_PORT")),
        "NAME": _env("SOURCE_POSTGRES_DB", _env("POSTGRES_DB", "paradigm_db"), "DASHBOARD_POSTGRES_DB"),
        "USER": os.getenv("SOURCE_POSTGRES_USER", DEFAULT_POSTGRES_USER),
        "PASSWORD": os.getenv("SOURCE_POSTGRES_PASSWORD", DEFAULT_POSTGRES_PASSWORD),
        "OPTIONS": {
            "connect_timeout": int(os.getenv("POSTGRES_CONNECT_TIMEOUT", "5")),
            **POSTGRES_KEEPALIVE_OPTIONS,
        },
    },
    "analytics": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": _env("ENERGY_AGG_POSTGRES_HOST", _env("POSTGRES_HOST", DEFAULT_POSTGRES_HOST, "DASHBOARD_POSTGRES_HOST")),
        "PORT": _env("ENERGY_AGG_POSTGRES_PORT", _env("POSTGRES_PORT", DEFAULT_POSTGRES_PORT, "DASHBOARD_POSTGRES_PORT")),
        "NAME": os.getenv("ENERGY_AGG_POSTGRES_DB", "student"),
        "USER": os.getenv("ENERGY_AGG_POSTGRES_USER", DEFAULT_POSTGRES_USER),
        "PASSWORD": os.getenv("ENERGY_AGG_POSTGRES_PASSWORD", DEFAULT_POSTGRES_PASSWORD),
        "OPTIONS": {
            "connect_timeout": int(os.getenv("POSTGRES_CONNECT_TIMEOUT", "5")),
            **POSTGRES_KEEPALIVE_OPTIONS,
        },
    },
}

ENERGY_POWER_TABLE = os.getenv("ENERGY_POWER_TABLE", "electricity_sensor_readings")
ENERGY_METADATA_DB_ALIAS = os.getenv("ENERGY_METADATA_DB_ALIAS", "source")
ENERGY_ANALYTICS_DB_ALIAS = os.getenv("ENERGY_ANALYTICS_DB_ALIAS", "analytics")
ENERGY_HOURLY_TABLE = os.getenv("ENERGY_HOURLY_TABLE", "student_schema.electricity_sensor_readings_hourly")
ENERGY_DAILY_TABLE = os.getenv("ENERGY_DAILY_TABLE", "student_schema.electricity_sensor_readings_daily")
ENERGY_DEFAULT_LOOKBACK_HOURS = int(os.getenv("ENERGY_DEFAULT_LOOKBACK_HOURS", "24"))

ANALYTICS_SERVICE_URL = os.getenv("ANALYTICS_SERVICE_URL", "http://127.0.0.1:8001")
ANALYTICS_SERVICE_TIMEOUT_SECONDS = float(os.getenv("ANALYTICS_SERVICE_TIMEOUT_SECONDS", "10"))
ANALYTICS_SERVICE_TOKEN = os.getenv("ANALYTICS_SERVICE_TOKEN", "")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",

    "CHECK_REVOKE_TOKEN": False,
    "REVOKE_TOKEN_CLAIM": "hash_password",
    "CHECK_USER_IS_ACTIVE": True,
}
